### ISSUE TITLE
params/global scope clarification wanted

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#224] opened 2023-09-25 13:49 UTC
Within

```
   "params" : {
      "global" : {
```

the following structure is provided:

```
"teststring" : "teststring.value.1",
"teststring" : "teststring.value.2",
${params.global.teststring} : "teststring.value.3",
"teststring" : "teststring.value.4"
```

Value is still

`"teststring.value.3"`

Expected:
`"teststring.value.4"`

**Comment by test-fullautomation** [comment] 2023-09-25 15:24
Hi Holger,
let us discuss this tomorrow when we meet.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment] 2023-09-26 08:02
Hi Son,
I found that this is a bug. Please check.
Thank you,
 Thomas

**Comment by namsonx** [comment] 2023-10-09 02:56
Hello Holger,

The root cause of this issue came from Jsonpreprocessor package, I had pushed the fix to [python-jsonpreprocessor (stabi branch)](https://github.com/test-fullautomation/python-jsonpreprocessor/tree/namsonx/task/stabi_branch).

Thank you,
Son

**Comment by test-fullautomation** [comment] 2023-10-09 09:32
Son waits for retest from Holger.

**Comment by HolQue** [comment] 2023-10-09 12:52
Retest successful (TSM_1200).

Issue can be closed.

**Closed as completed** 2023-10-09 13:00 UTC
Labels: bug, prio 1, 0.9.0
